name: vpn_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  auto_route: ^9.3.0
  country_flags: ^4.1.0
  flutter:
    sdk: flutter
  get_it: 9.0.5
  device_preview: ^1.3.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12
  auto_route_generator: ^9.2.2

flutter:
  uses-material-design: true
